-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 19:14:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Aula2Ex1_Jogo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Aula2Ex1_Jogo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aula2Ex1_Jogo` DEFAULT CHARACTER SET utf8 ;
USE `Aula2Ex1_Jogo` ;

-- -----------------------------------------------------
-- Table `Aula2Ex1_Jogo`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aula2Ex1_Jogo`.`tb_classe` (
  `id_classe` INT NOT NULL AUTO_INCREMENT,
  `nome_jogo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `nivel_jogo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aula2Ex1_Jogo`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aula2Ex1_Jogo`.`tb_personagem` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `nivel_forca` DOUBLE NOT NULL,
  `nivel_agilidade` DOUBLE NOT NULL,
  `nivel_ataque` DOUBLE NOT NULL,
  `nivel_defesa` DOUBLE NOT NULL,
  `fkid_classe` INT NOT NULL,
  PRIMARY KEY (`idtable1`, `fkid_classe`),
  INDEX `fk_tb_personagem_tb_classe_idx` (`fkid_classe` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`fkid_classe`)
    REFERENCES `Aula2Ex1_Jogo`.`tb_classe` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
